version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data

volumes:
  nifi_data: